dateModified: 1751436699
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'volume:5ea50ad3-92a6-4e91-b5eb-2acfb721f9e1'
      tableAttributes:
        - imageSize
        - alt
        - dateModified
        - link
      type: native
    -
      key: temp
      type: native
email:
  fromEmail: admin@example.com
  fromName: 'Craft CMS'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    036f6fb3-bd0b-4d7d-a2a6-7beb59204c1a: Default # Default
    a4f2973e-4934-46f7-af6d-b72af78abade: Primary # Primary
system:
  edition: solo
  live: true
  name: 'Craft CMS'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: $SYSTEM_TIMEZONE
